name: Node

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]
        
      steps:
      -name: yarn install, build, test
      run:
        yarn
        yarn start
        yarn jest
