name: Node

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: use nodejs to run test
        uses: actions/setup-node@v2

      - name: yarn install, build, test
        run: |
          echo hello world
          yarn
          yarn tsc
          yarn jest
          rm -rf node_modules
          yarn install --frozen-lockfile
